#!/usr/bin/env bash
# Script to install nginx and update default landing page
# and update the config file
sudo apt-get -y update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/eror1_404.html
sed -i "/redirect_me/ a\\\terror_page 404 /error1_404.html;" /etc/nginx/sites-available/default
service nginx restart
