#!/usr/bin/env bash
# Script to automate backup of database

# MySQL dump file name
dump_file="backup.sql"

# Compressed archive name format: day-month-year.tar.gz
archive_name=$(date +"%d-%m-%Y").tar.gz

# MySQL dump command
mysqldump --user=root --password="$1" --all-databases > "$dump_file"


# Create compressed archive
tar -czf "$archive_name" "$dump_file"
