#!/usr/bin/env bash
# This scripts kills a process given certain conditions

kil() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && kil' SIGTERM
  trap 'kil' SIGQUIT
done
